### ISSUE TITLE
Use multiple email API sender

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#188]
- [x] Add models #318 
- [x] Add a method to post multiple emails #324 
- [x] Add multiple page #319 
- [x] Add component for multiple Page #320 
- [x] Update Route to use new component #321 

Parent Issue: #187
