### ISSUE TITLE
Use multiple Notification API sender

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#190]
- [x] Add models #357 
- [x] Add a method to post multiple Notifications #358 
- [x] Add multiple page #359 
- [x] Add component for multiple Page #360 
- [x] Update Route to use new component #361 

Parent Issue: #187
