### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#335]
- [x] Upgrade to JHipster 7.2.0 #336 
- [x] Upgrade custom dependencies #337 
- [x] Run test to validate #338
