### ISSUE TITLE
Update Email to use RSQL

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#340]
- [x] Update email controller to use RSQL #343 
- [x] Update email tests to test RSQL #344 
- [x] Update email list to use RSQL for its search #345 

Parent Issue: #339
