### ISSUE TITLE
Update SMS to use RSQL

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#341]
- [x] Update SMS controller to use RSQL #346 
- [x] Update SMS test to test RSQL #347 
- [x] Update SMS list to use RSQL for its search #348 

Parent Issue: #339
