### ISSUE TITLE
Update Notification to use RSQL

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#342]
- [x] Update notification controller to use RSQL #349 
- [x] Update notification tests to test RSQL #350 
- [x] Update notification list to use RSQL for its search #351 

Parent Issue: #339
