### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by GLinBoy** [GLinBoy/MessageCentral#376]
- [x] com.github.kavenegar:kavenegar-java .................. v2.0.3 -> 2.0.3 #377 
- [x] com.google.firebase:firebase-admin .................... 8.0.1 -> 8.1.0 #378 
- [x] com.twilio.sdk:twilio ............................... 8.19.1 -> 8.20.0 #379
